### PR TITLE
Provide 404 page

### PR DESCRIPTION
**Pull request by weierophinney**
This patch adds the 404 page to the theme.

### CODE REVIEW

**Comment by froschdesign** [comment]
@weierophinney 
The correct fix should be done here: https://github.com/laminas/documentation-theme/blob/master/update_mkdocs_yml.py#L42

**Comment by froschdesign** [comment]
The file for 404 is already there: https://github.com/laminas/documentation-theme/blob/master/theme/pages/404.html

**Comment by weierophinney** [comment]
It is _now_. It wasn't _before_ (this patch added it).

**Comment by froschdesign** [comment]
Please look at the directory names: `theme` vs. `theme/pages` 😉

**Pull request merged**
