### PR TITLE
[Fix] README: Small typo & markdown

### PR DESCRIPTION
**Pull request by sjokkateer**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
Fixes one typo and one markdown URL in the readme of the github actions docs.

### CODE REVIEW

**Comment by sjokkateer** [comment]
I was wondering if [README#L25](https://github.com/laminas/documentation-theme/blob/master/github-actions/docs/README.md?plain=1#L25) should be `docs/html` instead of `doc/html`. If that is the case I'll gladly update that as well!

**Comment by froschdesign** [comment]
> If that is the case I'll gladly update that as well!

Go for it.
Thanks in advance! 👍

**Comment by sjokkateer** [comment]
> > If that is the case I'll gladly update that as well!
> 
> Go for it. Thanks in advance! 👍

@froschdesign I'm sorry to address you directly but does this PR suffice in its curent conidition?

**Review by froschdesign — APPROVED** [review]

**Comment by froschdesign** [comment]
@sjokkateer 
Thank you for your time and this contribution! 👍

**Pull request merged**
